In [1]:
import numpy as np

In [3]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3, 5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.random((3, 3))

array([[0.28583309, 0.25408862, 0.13919437],
       [0.13241073, 0.07567047, 0.08679362],
       [0.5578516 , 0.45771453, 0.42914186]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)
print("Nombre de dimensions de x1: ", x1.ndim)
print("Forme de x1: ", x1.shape)
print("Taille de x1: ", x1.size)
print("Type de x1: ", x1.dtype)

Nombre de dimensions de x1:  1
Forme de x1:  (6,)
Taille de x1:  6
Type de x1:  int32


In [19]:
print(x1)

[5 0 3 3 7 9]


In [20]:
print(x1[0])

5


In [21]:
print(x1[-1])

9


In [25]:
x2 = np.random.randint(10, size=(3, 4))
print(x2)

[[8 1 5 9]
 [8 9 4 3]
 [0 3 5 0]]


In [26]:
print(x2[0, 1])

1


In [28]:
x1[1] = 100
print(x1)

[  5 100   3   3   7   9]


In [29]:
x1[1] = 3.14
print(x1)

[5 3 3 3 7 9]


In [30]:
print(x1[:5])

[5 3 3 3 7]


In [31]:
print(x1[5:])

[9]


In [32]:
print(x1[::2])

[5 3 7]


In [33]:
print(x1[::-1])

[9 7 3 3 3 5]


In [34]:
print(x2[0,:])

[8 1 5 9]


In [36]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [38]:
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [39]:
def calcul_inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
print(calcul_inverse(values))

[0.33333333 0.25       0.11111111 0.5        0.25      ]


In [40]:
tableau_large = np.random.randint(1, 100, size=1000000)
%timeit calcul_inverse(tableau_large)

1.78 s ± 30 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [42]:
%timeit (1.0 / tableau_large)

4.11 ms ± 159 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [43]:
x = np.arange(4)
print("x = ", x)
print("x + 5 = ", x + 5)
print("x - 5 = ", x - 5)
print("x * 2 = ", x * 2)
print("x / 2 = ", x / 2)
print("x // 2 = ", x // 2)

x =  [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.5 1.  1.5]
x // 2 =  [0 0 1 1]


In [44]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


In [45]:
x = np.random.rand(3, 3)
x > 0.5

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [46]:
np.where(x > 0.5)

(array([0], dtype=int64), array([2], dtype=int64))

In [47]:
L = np.random.random(100)
np.sum(L)

54.58939404484368

In [48]:
%timeit sum(tableau_large)
%timeit np.sum(tableau_large)

78.8 ms ± 6.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
399 µs ± 3.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [49]:
M = np.random.random((3, 4))
print(M)

[[0.51324137 0.67519693 0.43960314 0.1163365 ]
 [0.44355178 0.24505542 0.64322067 0.25284067]
 [0.95285657 0.43699403 0.00529613 0.1335414 ]]


In [50]:
print("Somme de tous les éléments de M:", M.sum())
print("Somme des colonnes de M:", M.sum(axis=0))

Somme de tous les éléments de M: 4.8577345974657495
Somme des colonnes de M: [1.90964972 1.35724638 1.08811994 0.50271856]


In [51]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [52]:
a + 5

array([5, 6, 7])

In [53]:
M = np.ones((3, 3))
print(M)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [54]:
print(M + a)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [55]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

In [56]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])